### ISSUE TITLE
获取资源失败，WIN7

### ISSUE THREAD

**Issue by AllenJask** [52beijixing/smartedu-download#2]
https://basic.smartedu.cn/syncClassroom/classActivity?activityId=bac4d3d4-f187-4a9e-9b80-64c87e957537&chapterId=26ad62ac-8a0f-3a03-8b86-3bf51709d9aa&teachingmaterialId=5ce96672-f52f-4c2f-9c3d-016ed1415278&fromPrepare=0

![image](https://github.com/52beijixing/smartedu-download/assets/110995645/b3f9449a-dfcc-434e-91eb-b02446c471e9)

**Comment by 52beijixing** [comment]
> https://basic.smartedu.cn/syncClassroom/classActivity?activityId=bac4d3d4-f187-4a9e-9b80-64c87e957537&chapterId=26ad62ac-8a0f-3a03-8b86-3bf51709d9aa&teachingmaterialId=5ce96672-f52f-4c2f-9c3d-016ed1415278&fromPrepare=0
> 
> ![image](https://private-user-images.githubusercontent.com/110995645/346804294-b3f9449a-dfcc-434e-91eb-b02446c471e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTUxNjAsIm5iZiI6MTcyMDUxNDg2MCwicGF0aCI6Ii8xMTA5OTU2NDUvMzQ2ODA0Mjk0LWIzZjk0NDlhLWRmY2MtNDM0ZS05MWViLWIwMjQ0NmM0NzFlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQwODQ3NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MWFkNDdjNzRiNDBiMDZkYmUzNzRhZDRjMjgxNzE5OGFjMTBhYmRiOGViODYxZDI1MWZjOTk4MDVjZDcyZDk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Nm6r7nC8BBYP9-d81pqnz4KSEtP-6Au2Ii9k23dWAkc)

您是否使用了代理，或者抓包工具，这个应该是网络问题导致的。
