### ISSUE TITLE
m3u8/win7版本解析失败

### ISSUE THREAD

**Issue by huiwin** [52beijixing/smartedu-download#3]
解析的地址是：https://basic.smartedu.cn/syncClassroom/classActivity?activityId=89306b9d-db26-4db5-9f39-54865d43314b&chapterId=760571c7-a8d5-3218-a0f5-aaea5091f5ff&teachingmaterialId=2aa68399-4700-4030-8973-457cf32384dc&fromPrepare=0
logo文件已上传
[Logs.zip](https://github.com/user-attachments/files/16152407/Logs.zip)

**Comment by 52beijixing** [comment]
> 解析的地址是：https://basic.smartedu.cn/syncClassroom/classActivity?activityId=89306b9d-db26-4db5-9f39-54865d43314b&chapterId=760571c7-a8d5-3218-a0f5-aaea5091f5ff&teachingmaterialId=2aa68399-4700-4030-8973-457cf32384dc&fromPrepare=0 logo文件已上传 [Logs.zip](https://github.com/user-attachments/files/16152407/Logs.zip)

哥，我查看了Logs，您可能是弄错了，不是打开N_m3u8DL-CLI_v3.0.2.exe然后输入链接，应该是打开smartedu-download.exe输入链接。

N_m3u8DL-CLI_v3.0.2.exe和ffmpeg.exe是帮助下载m3u8转为mp4格式的。

**Comment by huiwin** [comment]
> > 解析的地址是：https://basic.smartedu.cn/syncClassroom/classActivity?activityId=89306b9d-db26-4db5-9f39-54865d43314b&chapterId=760571c7-a8d5-3218-a0f5-aaea5091f5ff&teachingmaterialId=2aa68399-4700-4030-8973-457cf32384dc&fromPrepare=0 logo文件已上传 [Logs.zip](https://github.com/user-attachments/files/16152407/Logs.zip)
> 
> 哥，我查看了Logs，您可能是弄错了，不是打开N_m3u8DL-CLI_v3.0.2.exe然后输入链接，应该是打开smartedu-download.exe输入链接。
> 
> N_m3u8DL-CLI_v3.0.2.exe和ffmpeg.exe是帮助下载m3u8转为mp4格式的。

这不就尴尬了、第一次使用见谅😰😰😰、咱们的软件很好用支持哈

**Comment by 52beijixing** [comment]
> > > 解析的地址是：https://basic.smartedu.cn/syncClassroom/classActivity?activityId=89306b9d-db26-4db5-9f39-54865d43314b&chapterId=760571c7-a8d5-3218-a0f5-aaea5091f5ff&teachingmaterialId=2aa68399-4700-4030-8973-457cf32384dc&fromPrepare=0 logo文件已上传 [Logs.zip](https://github.com/user-attachments/files/16152407/Logs.zip)
> > 
> > 
> > 哥，我查看了Logs，您可能是弄错了，不是打开N_m3u8DL-CLI_v3.0.2.exe然后输入链接，应该是打开smartedu-download.exe输入链接。
> > N_m3u8DL-CLI_v3.0.2.exe和ffmpeg.exe是帮助下载m3u8转为mp4格式的。
> 
> 这不就尴尬了、第一次使用见谅😰😰😰、咱们的软件很好用支持哈

没事，也是我一开始偷懒没有详细介绍说明。您到时候试一下能否使用，可以的话我就关闭这个issue了。

**Comment by huiwin** [comment]
> > > > 解析的地址是：https://basic.smartedu.cn/syncClassroom/classActivity?activityId=89306b9d-db26-4db5-9f39-54865d43314b&chapterId=760571c7-a8d5-3218-a0f5-aaea5091f5ff&teachingmaterialId=2aa68399-4700-4030-8973-457cf32384dc&fromPrepare=0 logo文件已上传 [Logs.zip](https://github.com/user-attachments/files/16152407/Logs.zip)
> > > 
> > > 
> > > 哥，我查看了Logs，您可能是弄错了，不是打开N_m3u8DL-CLI_v3.0.2.exe然后输入链接，应该是打开smartedu-download.exe输入链接。
> > > N_m3u8DL-CLI_v3.0.2.exe和ffmpeg.exe是帮助下载m3u8转为mp4格式的。
> > 
> > 
> > 这不就尴尬了、第一次使用见谅😰😰😰、咱们的软件很好用支持哈
> 
> 没事，也是我一开始偷懒没有详细介绍说明。您到时候试一下能否使用，可以的话我就关闭这个issue了。

可以使用的、我已经测试好了、挺全面的。
