### ISSUE TITLE
是否可以增加如下地址的下载。

### ISSUE THREAD

**Issue by pubytu** [52beijixing/smartedu-download#8]
https://www.hnqrzzxx.com/index.php/Video/view/aid/5450.html
要跳过登陆权限

**Comment by 52beijixing** [comment]
> https://www.hnqrzzxx.com/index.php/Video/view/aid/5450.html 要跳过登陆权限

该网站非国家中小学智慧教育平台，不增加此网站下载功能。**但是为解决此Issue，给您提供下面解决方案**：

您给出的地址如需要跳过登录权限，可访问：http://www.hnqrzzxx.com/index.php/Video/view/aid/5450/isfree/1.html

如需登录地址为：http://www.hnqrzzxx.com/index.php/Video/view/aid/1241.html

取其1241参数，构造出无登录访问地址：http://www.hnqrzzxx.com/index.php/Video/view/aid/1241/isfree/1.html

随后，您可通过浏览器安装插件猫抓获取视频地址进行下载，视频未加密！


**如解决您的问题，请您回复或关闭此Issue**
